name: CI/CD

on:
  push:
    tags: "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: pull repository
        uses: actions/checkout@v4

      - name: check files
        run: |
          ls -alh
          tree .

      - name: args setup
        run: |
          echo "PROJECT_NAME=$(basename ${{ github.repository }})" >> $GITHUB_ENV
          echo "TAG_NAME=$(basename ${{ github.ref }})" >> $GITHUB_ENV
          echo "RELEASE_NAME=$(basename ${{ github.repository }})-$(basename ${{ github.ref }})" >> $GITHUB_ENV

      - name: check args
        run: |
          echo "PROJECT_NAME=$PROJECT_NAME"
          echo "TAG_NAME=$TAG_NAME"
          echo "RELEASE_NAME=$RELEASE_NAME"

      - name: create release assets
        run: |
          mkdir _temp_workspace _temp_release_assets
          cp -a src/. _temp_workspace/
          rm -rf _temp_workspace/tests
          (cd _temp_workspace && zip -r ../_temp_release_assets/$RELEASE_NAME.zip .)

      - name: check files
        run: |
          ls -alh
          tree .

      - name: upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: _temp_release_assets/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}